### ISSUE TITLE
How to include an extra action as well as one extra bonus action for allies?

### ISSUE THREAD

**Issue by GottaSlay** [Zehtukae/combat-extender#21]
Hi! I'm wondering how to edit the JSON file to include one extra action as well as one extra bonus action for Allies. So far I've tried copying the same structure as that segment for "Bosses" and "Enemies", but I see no changes in game. Is something wrong with the code I put in, or does "Allies" not include the player/party? I've tried saving and reloading, entering combat etc but there is no change.

[CombatExtender.json](https://github.com/Zehtukae/combat-extender/files/14397371/CombatExtender.json) 
![image](https://github.com/Zehtukae/combat-extender/assets/43540181/47929ad7-03f0-4217-89d1-54d2152786e7)

**Comment by Zehtukae** [comment]
Hey, that is correct. The active player(s) and party are excluded. There are other mods that can give you an extra action or bonus action as player like https://www.nexusmods.com/baldursgate3/mods/598

**Comment by GottaSlay** [comment]
Oh, I see! I'll try that mod out then. And thank you so much for the quick reply and the amazing work you've done with this mod. I've found that the AI gives so much enjoyment to my playthrough. Downloaded and endorsed!
